### ISSUE TITLE
Login via Facebook

### ISSUE THREAD

**Issue by tleekkul** [KayEss/odin#14]
# Proposal
Supporting login via Facebook in Odin. Odin must validate facebook access tokens with facebook appID and secret before record to the database and return JWT to client

# Implementation

## modules opts/facebook
- Create table `facebook_credentials` and `facebook_credentials_ledger`
- Have trigger after insert to `facebook_credentials_ledger` to populate `facebook_credentials` table

## Odin API
Odin view: `odin.login.facebook`
POST `/odin/api/login-facebook`
Payload
```
{"access_token": "<FACEBOOK_ACCESS_TOKEN>"}
```
Response `minted JWT`

## Other
- Odin must be able to config `facebook_app_id` and `facebook_app_secret`

**Comment by KayEss** [comment]
Do we create a new column in the identity table for this? What happens if we get a request with a JWT already? I assume we don't yet do the linking?

**Comment by KayEss** [comment]
> Do we create a new column in the identity table for this?
Actually I meant to ask if we add a new row, I guess both questions are valid.

**Comment by tleekkul** [comment]
**Do we create a new column in the identity table for this?** 
No, `facebook_credentials` should be one-to-one with `identity`

**What happens if we get a request with a JWT already? I assume we don't yet do the linking?**
This should be another feature. We have not supported the linking yet.

**Comment by KayEss** [comment]
>> Do we create a new column in the identity table for this?

> No, facebook_credentials should be one-to-one with identity

So we could add this as a new column to the `credentials` table? I wonder if that's a smart or stupid idea....

**Comment by tleekkul** [comment]
I think we should treat Facebook the same as the credential table but I also wonder what happened when we are going to have applications concept in odin.
