### ISSUE TITLE
odin.user embedded in request

### ISSUE THREAD

**Issue by tleekkul** [KayEss/odin#3]
Need to be able to reference odin.user in view configuration, so that we can authorize resource based on logged-in user.

**Usage (In fostgres views configuration)**
```
{
  "views/pet": {
    "sql":  [{
      "path": [],
      "GET": "SELECT pet_name, pet_age from pet WHERE owner=odin.user
    }]
   }
}
```

**Comment by codewithcats** [comment]
#5

**Comment by KayEss** [comment]
This is now done. It's been in develop for a while now.
