### ISSUE TITLE
Add all JWT values to Odin secure view

### ISSUE THREAD

**Issue by codewithcats** [KayEss/odin#4]
Initial idea from @KayEss 

> Should we iterate over all of the JWT payload to add? I think it might be an idea
> This file contains the headers class: https://github.com/KayEss/fost-internet/blob/master/Cpp/include/fost/headers.hpp
> There is an iterator for the header content: https://github.com/KayEss/fost-internet/blob/master/Cpp/include/fost/headers.hpp#L116
> Something like
> for ( const auto &sv : headers()["__jwt"] ) {
>    cnx.set_session("odin.jwt." + sv.first, sv.second);
> }
> The map iterator will give you a pair on the key and the value

**Comment by KayEss** [comment]
These are now all accessible.
